language: R
sudo: required
warnings_are_errors: false
global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual"

r_binary_packages:
  - MASS
  - dplyr
  - ggplot2
  - testthat
  - rmarkdown
  - classInt

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
